Algoritmo "Tabuáda"
// Descrição   : Algoritmo que dado um número informado pelo usuário, inmprime a tabuáda dela de 1 a 10
// Autor(a)    : Silas Andrade
// Data atual  : 08/08/2024
Var
// Seção de Declarações das variáveis 
j : real
num : real

Inicio
j <- 0
Escreva("Digite um número: ")
leia(num)
enquanto j <= 10 faca
Escreva(num)
Escreva(" *")
Escreva(j, " =")
Escreval(num * j)
j <- j + 1
fimenquanto


Fimalgoritmo
